# test of signal EJ showering from PowHeg-generated sample

executable = /gfsvol01/atlas/giuliac/HiddenValley_Higgs/tasks/20250616_Task23/test_showering.sh

getenv=True

request_cpus = 1
request_memory = 2048
request_disk = 10000000

log = /gfsvol01/atlas/giuliac/condor/20250616_Task23/condor_out/test_showering_signal_EJ_job_$(Item).log
output = /gfsvol01/atlas/giuliac/condor/20250616_Task23/condor_out/test_showering_signal_EJ_job_$(Item).out
error = /gfsvol01/atlas/giuliac/condor/20250616_Task23/condor_out/test_showering_signal_EJ_job_$(Item).err

notification = complete
notify_user = giulia.cossutti@cern.ch

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue
