# 50K background events: Z + jets from gamma, Z decay to charged leptons

executable = /gfsvol01/atlas/giuliac/HiddenValley_Higgs/tasks/20250513_Task19/50K_bkg_Zjets_gamma.sh

getenv=True

request_cpus = 1
request_memory = 2048
request_disk = 10000000

log = /gfsvol01/atlas/giuliac/condor/20250513_Task19/50K_bkg_Zjets_gamma_job.log
output = /gfsvol01/atlas/giuliac/condor/20250513_Task19/50K_bkg_Zjets_gamma_job.out
error = /gfsvol01/atlas/giuliac/condor/20250513_Task19/50K_bkg_Zjets_gamma_job.err

notification = complete
notify_user = giulia.cossutti@cern.ch

should_transfer_files = Yes
when_to_transfer_output = ON_EXIT

queue
