# 500K background events: diboson ZZ to charged leptons and b quarks

executable = /gfsvol01/atlas/giuliac/HiddenValley_Higgs/tasks/20250717_Task27/500K_bkg_ZZ_JES.sh
arguments = $(Item)

getenv=True

request_cpus = 1
request_memory = 2048
request_disk = 10000000

log = /eos/infnts/atlas/giuliac/condor/20250717_Task27/condor_out/bkg_ZZ_JES_job_$(Item).log
output = /eos/infnts/atlas/giuliac/condor/20250717_Task27/condor_out/bkg_ZZ_JES_job_$(Item).out
error = /eos/infnts/atlas/giuliac/condor/20250717_Task27/condor_out/bkg_ZZ_JES_job_$(Item).err

notification = complete
notify_user = giulia.cossutti@cern.ch

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue from seq 1 10 |
