# 500K signal Emerging Jet events to produce Higgs boson and HiddenValley jets with Reclustered jet pTmin = 40 GeV, dark matter decay to b bbar, Z decay to charged leptons

executable = /gfsvol01/atlas/giuliac/HiddenValley_Higgs/tasks/20250717_Task27/500K_signal_EJ.sh
arguments = $(Item)

getenv=True

request_cpus = 1
request_memory = 2048
request_disk = 10000000

log = /eos/infnts/atlas/giuliac/condor/20250717_Task27/condor_out/signal_EJ_job_$(Item).log
output = /eos/infnts/atlas/giuliac/condor/20250717_Task27/condor_out/signal_EJ_job_$(Item).out
error = /eos/infnts/atlas/giuliac/condor/20250717_Task27/condor_out/signal_EJ_job_$(Item).err

notification = complete
notify_user = giulia.cossutti@cern.ch

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

queue from seq 1 10 |
